ASSIGNMENT 1

NAME: R.B.SHREYAS, REGN: 21BAI1220, CAMPUS: VIT CHENNAI,  
                    LINK: https://colab.research.google.com/drive/1mOM3r5y3YwCVJBQmB4jadn2dC9wfp5b-?usp=sharing

In [1]:
import pandas as pd
import numpy as np

In [10]:
#Task - 1 Create a pandas dataframe (DataFrame name as 'df') (10 observation and 5 features)
data = np.random.rand(10, 5)
df = pd.DataFrame(data, columns=['Feature 1', 'Feature 2', 'Feature 3', 'Feature 4', 'Feature 5'])
df

   Feature 1  Feature 2  Feature 3  Feature 4  Feature 5
0   0.847559   0.374331   0.364332   0.468796   0.939452
1   0.373822   0.766055   0.822059   0.620051   0.238035
2   0.998352   0.226777   0.676456   0.263700   0.657794
3   0.416387   0.947606   0.882291   0.502455   0.780893
4   0.383908   0.652652   0.174333   0.275981   0.483522
5   0.479846   0.966770   0.150597   0.800838   0.380577
6   0.014956   0.470696   0.905467   0.365717   0.200680
7   0.459647   0.910847   0.921827   0.478056   0.147972
8   0.249001   0.918435   0.655411   0.427670   0.426100
9   0.851640   0.505679   0.992309   0.891667   0.561203

In [12]:
#Task- 2 Check the info of 'df'
df_info = df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Feature 1  10 non-null     float64
 1   Feature 2  10 non-null     float64
 2   Feature 3  10 non-null     float64
 3   Feature 4  10 non-null     float64
 4   Feature 5  10 non-null     float64
dtypes: float64(5)
memory usage: 528.0 bytes

In [13]:
#Task 3- Check the descriptive statistics of 'df'
descriptive_stats = df.describe()
descriptive_stats

       Feature 1  Feature 2  Feature 3  Feature 4  Feature 5
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.507512   0.673985   0.654508   0.509493   0.481623
std     0.303485   0.267670   0.315821   0.207676   0.258075
min     0.014956   0.226777   0.150597   0.263700   0.147972
25%     0.376344   0.479442   0.437102   0.381205   0.273670
50%     0.438017   0.709353   0.749257   0.473426   0.454811
75%     0.755630   0.916538   0.899673   0.590652   0.633646
max     0.998352   0.966770   0.992309   0.891667   0.939452

In [14]:
#Task 4- check the 4th index observation with 'loc' slicing operator.
observation_4 = df.loc[4]
observation_4

Feature 1    0.383908
Feature 2    0.652652
Feature 3    0.174333
Feature 4    0.275981
Feature 5    0.483522
Name: 4, dtype: float64

In [9]:
#Task 5 - Check the null values in your 'df'
null_values = df.isnull().sum()
null_values

Feature 1    0
Feature 2    0
Feature 3    0
Feature 4    0
Feature 5    0
dtype: int64